# Generated by Django 6.0.3 on 2026-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rfq_buyer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='buyer_type',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual Buyer'), ('company', 'Company Buyer'), ('establishment', 'Commercial Establishment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer_individual', 'Buyer Individual'), ('buyer_company', 'Buyer Company'), ('buyer_establishment', 'Buyer Establishment'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='buyer_individual', max_length=30),
        ),
    ]
