# Generated by Django 5.2.13 on 2026-04-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer_individual', 'Buyer Individual'), ('buyer_company', 'Buyer Company'), ('buyer_establishment', 'Commercial Establishment'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='buyer_individual', max_length=30),
        ),
    ]
