# Generated by Django 6.0.4 on 2026-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_supplierprofile_commercial_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/'),
        ),
    ]
