# Generated by Django 6.0.3 on 2026-04-27 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_rejection_reason_alter_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit/Debit Card'), ('moyasar', 'Moyasar'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('stripe', 'Stripe'), ('credit_terms', 'Credit Terms')], default='bank_transfer', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.order')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
